---
apiVersion: v1
kind: Service
metadata:
  annotations:
    projectcontour.io/upstream-protocol.tls: "443"
  labels:
    app: uaa-deployment
  name: uaa
spec:
  ports:
  - name: web
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: uaa-deployment
  type: ClusterIP
